### ISSUE TITLE
Requesting permissions on this repo for kasts developers

### ISSUE THREAD

**Issue by mogwa1** [flathub/org.kde.kasts#21]
As discussed in the KDE flatpak matrix channel, we would like the main developers of kasts to get permissions on this flathub app repo.  These are (github user names):
- @mogwa1 (myself)
- @TobiasFella

**Comment by travier** [comment]
@flathub/admins Could one of you make that happen? Thanks!

**Comment by bilelmoussaoui** [comment]
Done

**Comment by travier** [comment]
Thanks!
